// actions
export const LOGGING = 'LOGGING';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTERING = 'REGISTERING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const GET_ALL_LIST_ING = 'GET_ALL_LIST_ING';
export const GET_ALL_LIST_SUCCESS = 'GET_ALL_LIST_SUCCESS';
export const GET_ALL_LIST_FAILED = 'GET_ALL_LIST_FAILED';
export const GET_MY_LIST_ING = 'GET_MY_LIST_ING';
export const GET_MY_LIST_SUCCESS = 'GET_MY_LIST_SUCCESS';
export const GET_MY_LIST_FAILED = 'GET_MY_LIST_FAILED';
export const SET_LIST_FORM = 'SET_LIST_FORM';
export const SET_LIST_INDEX = 'SET_LIST_INDEX';
